platform :ios,'7.0'

target 'TYUpdatePrompt_Example' do
  pod 'TYUpdatePrompt', :path => '../'
  pod 'Masonry'

  target 'TYUpdatePrompt_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs'
    pod 'Kiwi'
  end
end
